Promote buf convert to stable
bufbuild/buf pull request #1574
Opened 2022-11-09 15:25 UTC by joshcarp

Promotes `buf beta convert` to stable. 
Keeps `buf beta convert` so that anyone who's using it may continue until we decide to remove it from beta.

2022-12-01 19:37 UTC, elliotmjackson commented on private/buf/cmd/buf/buf.go
> +					//convert.NewCommand("convert", builder),
```suggestion
```

2022-12-01 19:38 UTC, elliotmjackson requested changes

2022-12-01 19:38 UTC, elliotmjackson commented on private/buf/cmd/buf/buf.go
> +					//convert.NewCommand("convert", builder),
```suggestion
```

2022-12-01 19:39 UTC, elliotmjackson commented on private/buf/cmd/buf/buf.go
> +					//convert.NewCommand("convert", builder),
or do you want to uncomment it?

2022-12-01 23:47 UTC, twilly approved these changes
:shipit:

2022-12-02 00:40 UTC, elliotmjackson approved these changes

2022-12-02 14:31 UTC, merged