Include rule name in breaking change output
bufbuild/buf pull request #1823
Opened 2023-02-10 18:38 UTC by tonyli233

Proposed by [this issue](https://github.com/bufbuild/buf/issues/1799), I added `PrintOption` type for `PrintFileAnnotations` in `bufanalysis.bufanalysis.go`. Now printing file annotations can include rule name or exclude rule name depending on situation.

2023-02-10 18:54 UTC, joshcarp commented
can you add some tests around this?

2023-02-10 19:02 UTC, bufdev requested changes
We don't necessarily want to do this - the existing behavior is as intended, need to think about this more.

2023-02-10 19:08 UTC, tonyli233 commented
> can you add some tests around this?

Yep I just refactored the old tests around this.

2023-02-10 19:08 UTC, tonyli233 commented
> We don't necessarily want to do this - the existing behavior is as intended, need to think about this more.

Yeah so I'm keeping this PR as a draft until we have more thoughts.

2023-02-22 19:27 UTC, bufdev commented
Having considered this more, and re: https://github.com/bufbuild/buf/issues/1799, I think we're going to punt on any changes here for now, so will close this.

2023-02-22 19:27 UTC, closed without merging