feat: linter only report new problems
bufbuild/buf pull request #1859
Opened 2023-02-25 09:34 UTC by xiaoyawei

## What's this PR about

Similar to what was released in [golangci-lint](https://github.com/golangci/golangci-lint/blob/master/CHANGELOG.md#september-2021), this PR allows buf linter to find new issues from a diff.

## Why is it needed

There are times when someone wants to add buf linter for an existing repo, with many existing issues. Some of such changes cannot even be fixed without a breaking change, and hereby has to stay as is. With this feature, people can add linter for an existing repo, which will work to detect new issues in the future.

## Reviewers

@jhump (Looks like you were the most active contributor recently. Not sure whether you will be the right reviewer and feel free to pass this PR to someone else)

2023-02-25 09:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bufbuild/buf?pullRequest=1859) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bufbuild/buf?pullRequest=1859) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bufbuild/buf?pullRequest=1859) it.</sub>

2023-02-27 16:06 UTC, bufdev requested changes
We appreciate the efforts here! This does look like something that would be useful if it could work. Unfortunately I'm concerned that it won't work in `buf`'s case - this seems to rely on `buf` only processing local git repositories, whereas `buf` may be processing directories, tarballs, zip files, remote git repositories, or images. We'd also have to make sure the UX is carefully thought through.

The traditional way to accomplish what you'd like to with `buf` (ignore existing errors) is to do a run with `buf lint --error-format=config-ignore-yaml`, copying and pasting the result into your `buf.yaml`. Does this not work for you/what is insufficient here?

I've made some comments on the PR, but I think we're unlikely to accept it in its current form. Again, thanks for the efforts though.

2023-02-27 16:06 UTC, bufdev commented on private/buf/cmd/buf/command/lint/lint.go
> +	checker := revgrep.Checker{
`revgrep` seems to only work with a local directory, whereas `buf` works with local directories (git or not git), tarballs, zip files, remote git repositories, and images. I don't think `revgrep` works as a general solution for `buf` here unless I'm missing something

2023-02-27 16:24 UTC, xiaoyawei commented
> The traditional way to accomplish what you'd like to with buf (ignore existing errors) is to do a run with buf lint --error-format=config-ignore-yaml, copying and pasting the result into your buf.yaml. Does this not work for you/what is insufficient here?

@bufdev thanks for the suggestion but I am afraid it is not sufficient. If I did what you suggested, then I can't prevent people from making bad changes in an existing file; instead, for new changes that break linting rules in an existing file, I would like `buf lint` can catch them as well.

What I was trying to achieve is very similar to that in `golangci-lint` (https://github.com/golangci/golangci-lint/blob/f4fec8c6d0700e6a3e20835d04995ea5c9ee9087/pkg/commands/run.go#L232-L244)

2023-02-27 16:30 UTC, bufdev commented
In a given file, they could have more bad changes for a the single lint rule that is ignore yes, but that seems like mostly an edge case right?

You're welcome to pursue this PR with (1) no dependencies on revgrep (2) making sure it fits idiomatically into the existing codebase (3) it accounts for all the possible [inputs](https://docs.buf.build/reference/inputs), it will be a significant change though, and we can't promise acceptance.

2023-02-27 16:40 UTC, xiaoyawei commented
@bufdev thanks for the feedback

> In a given file, they could have more bad changes for a the single lint rule that is ignore yes, but that seems like mostly an edge case right?

It can't be an edge case for sure. For example, in a file consisting of multiple RPC definitions, some RPC names could be badly formatted; new changes on that file could also possibly suffer from similar issues, especially given the fact that junior engineers tend to follow the existing naming format in the same file, no matter whether that's appropriate or not.

> You're welcome to pursue this PR with (1) no dependencies on revgrep (2) making sure it fits idiomatically into the existing codebase (3) it accounts for all the possible [inputs](https://docs.buf.build/reference/inputs), it will be a significant change though, and we can't promise acceptance.

I would suggest that we could probably this change for `git` only, and handle all edge case (e.g., this feature won't work otherwise `buf lint` is running on a local git repo). Down the road, this change is to solve issues in CI, where 1) 90+% of people use `git` for version management and 2) CI usually runs on a git repo.

It's fine that this change does not get accepted and I totally understand all the concerns from the perspective of the buf owners. I would probably use a forked version with my changes here in my team, which I think is allowed by the license (Apache-2.0) used by this project, if it takes too much efforts to get this PR through to the codebase.

However, I would like to ask you to give it a second thought, that this feature is a super useful one for CI, and common seen in many existing (and widely-used) linters.

2023-02-27 16:44 UTC, bufdev commented
For cases where you want to make sure it's just ignoring one specific area, you can use comment ignores https://docs.buf.build/configuration/v1/buf-yaml#allow_comment_ignores. We have an issue tracked in https://github.com/bufbuild/buf/issues/558 to auto-add comment ignores on a first pass, along with code that actually works for it - we'd be more likely to pursue that issue than implement this here.

We're not comfortable having divergent behavior just for `git` - that would be significantly problematic within this codebase. You're totally welcome to maintain your fork obviously for your team :-) I'm going to close this as it sounds like the (large amount of) work to get this working across all inputs isn't something you'd want to take on, which is totally reasonable.

2023-02-27 16:44 UTC, closed without merging